name: npm-install-with-retries
description: "wraps npm install with retries/timeout to handle network failures"
inputs:
  ignore-scripts:
    default: 'false'
    description: "Skip pre/post install scripts"
runs:
  using: composite
  steps:
    - name: npm install
      uses: llmzy/github-workflows/.github/actions/retry@main
      with:
        command: npm config set fetch-timeout 600000 && npm install ${{ inputs.ignore-scripts == 'true' && '--ignore-scripts' || '' }} 
