on:
  workflow_call:
    secrets:
      SVC_CLI_BOT_GITHUB_TOKEN:
        description: A Github PAT with repo write access.
        required: true
      LLMZY_CI_EMAIL:
        description: Email address for Git commits
        required: true
      LLMZY_CI_PRIVATE_KEY:
        description: Private key for Git commit signing
        required: true

jobs:
  publish:
    runs-on: "ubuntu-latest"
    env:
      GITHUB_TOKEN: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn

      - uses: llmzy/github-workflows/.github/actions/yarnInstallWithRetries@main

      - name: Get Github user info
        id: github-user-info
        uses: llmzy/github-workflows/.github/actions/getGithubUserInfo@main
        with:
          SVC_CLI_BOT_GITHUB_TOKEN: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}

      - name: Configure Git signing
        uses: llmzy/github-workflows/.github/actions/configureGitSigning@main
        with:
          email: ${{ secrets.LLMZY_CI_EMAIL }}
          private_key: ${{ secrets.LLMZY_CI_PRIVATE_KEY }}
          github_token: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}

      - name: Build docs
        run: |
          rm -rf docs
          git worktree prune
          git fetch origin gh-pages:gh-pages
          git worktree add docs gh-pages
          yarn docs

      - name: Send to git
        run: |
          cd docs
          git add .
          git commit -m 'docs: publishing gh-pages [skip ci]' --no-verify
          git push origin gh-pages --no-verify

      - name: Cleanup Git signing
        if: always()
        uses: llmzy/github-workflows/.github/actions/cleanupGitSigning@main
